name: MiniHouse-AI

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать код
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Установить библиотеки
        run: pip install -r requirements.txt

      - name: Запустить бота
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: python bot.py
